server:
  port: ${PORT:8080}

spring:
  web:
    resources:
      static-locations: file:images/
  application:
    name: rooms-ms
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_URL}
    consumer:
      group-id: rooms-ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    topics:
      REVIEW_CREATED_TOPIC: REVIEW_CREATED_TOPIC

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring-application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/

cloud:
  aws:
    s3:
      region: ${S3_BUCKET_REGION:sa-east-1}
      bucket:
        name: ${S3_BUCKET_NAME:filesystem}

springdoc:
  swagger-ui:
    path: /api/rooms/swagger-ui.html
  api-docs:
    path: /api/rooms/v3/api-docs

com:
  amazonaws:
    xray:
      emitters:
        daemon-address: 127.0.0.1:2000