spring:
  application:
    name: rooms-microservice
  datasource:
    url: jdbc:h2:mem:testDb
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false